name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Continuous-Integration-Job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install additional dependencies if needed
          pip install -r requirements.txt

      - name: Run Robot Framework tests
        env:
          WORK_TOKEN: ${{ secrets.GIT_TOKEN }}
          TZ: America/Sao_Paulo
        run: |
          if ! robot --outputdir results --exclude skip Tests/; then
            echo "Robot Framework tests failed. Rerunning failed tests..."
            if [ -f results/output.xml ]; then
              robot --rerunfailed results/output.xml --outputdir results_rerun Tests/ || true
              if [ -f results_rerun/output.xml ]; then
                rebot --output results/output.xml --log results/log.html --report results/report.html --merge results/output.xml results_rerun/output.xml
              else
                echo "No output.xml file found from rerun. Skipping merge."
              fi
            else
              echo "No output.xml file found. Cannot rerun failed tests."
            fi
          fi
        
          echo "Script execution completed"
        continue-on-error: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./results
          name: robot-test-results
          retention-days: 3




